# Generated by Django 5.2.3 on 2025-06-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='Email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
